### ISSUE TITLE
matches3d order

### ISSUE THREAD

**Issue by edgarriba** [wg-perception/tod#10]
Hey Vincent!

I'm looking in how the 3d matches are encoded inside the matrix but I don't get a clear idea. What I see it's for each descriptor two 3d points are associated. Maybe  for the pnp we need to build a new container inside the DescriptorMatcher class to keep tracking the 2d and 3d correspondences. Take a look at this part and give me your opinion.

:DD

**Comment by vrabaud** [comment]
which file, which matrix ? DMatch in OpenCV references the points it matches. It's up to the user to have those points contain the required information (like their 2d position)

**Comment by edgarriba** [comment]
Yeah, I know. What I mean is in src/detection/DescriptorMatcher.cpp where for each descriptor matched in the scene, tw 3d points are associated to this descriptor and embedded into a matrix called matches_3d which then is passed to src/detection/GuessGenerator.cpp to estimate the object pose. I wanted to use this matrix to get the 2d position of each descriptor. I tried but I'm not sure if I'm using correctly the 3d matches because I don't a correct pose in the end. Here is my code: https://github.com/edgarriba/tod/blob/master/src/detection/GuessGenerator.cpp [line 174]

**Comment by edgarriba** [comment]
solved in 5737a517b1f07dad67305b8c3f5d5e5941e31768
