### ISSUE TITLE
Needed RGBD module with OpenCV3

### ISSUE THREAD

**Issue by edgarriba** [wg-perception/tod#9]
After OpenCV3 migration the rgbd module has been moved to opencv_contrib and some functions found there are needed. Could we add the rgbd module from opencv_contrib to ros-opencv3?

**Comment by edgarriba** [comment]
@vrabaud in the current version I have some compilation errors related to rgbd module

**Comment by vrabaud** [comment]
the RGBD module from the OpenCV repo does not compile with OpenCV3 ?

**Comment by edgarriba** [comment]
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp:42:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp: In function ‘bool cv::isValidDepth(const short int&)’:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:68:22: error: ‘numeric_limits’ is not a member of ‘std’
     return (depth != std::numeric_limits<short int>::min()) && (depth != std::numeric_limits<short int>::max());
                      ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:68:42: error: expected primary-expression before ‘short’
     return (depth != std::numeric_limits<short int>::min()) && (depth != std::numeric_limits<short int>::max());
                                          ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:68:42: error: expected ‘)’ before ‘short’
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp: In function ‘bool cv::isValidDepth(const short unsigned int&)’:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:74:22: error: ‘numeric_limits’ is not a member of ‘std’
     return (depth != std::numeric_limits<unsigned short int>::min())
                      ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:74:42: error: expected primary-expression before ‘unsigned’
     return (depth != std::numeric_limits<unsigned short int>::min())
                                          ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:74:42: error: expected ‘)’ before ‘unsigned’
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp: In function ‘bool cv::isValidDepth(const int&)’:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:81:22: error: ‘numeric_limits’ is not a member of ‘std’
     return (depth != std::numeric_limits<int>::min()) && (depth != std::numeric_limits<int>::max());
                      ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:81:42: error: expected primary-expression before ‘int’
     return (depth != std::numeric_limits<int>::min()) && (depth != std::numeric_limits<int>::max());
                                          ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:81:42: error: expected ‘)’ before ‘int’
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp: In function ‘bool cv::isValidDepth(const unsigned int&)’:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:87:22: error: ‘numeric_limits’ is not a member of ‘std’
     return (depth != std::numeric_limits<unsigned int>::min()) && (depth != std::numeric_limits<unsigned int>::max());
                      ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:87:42: error: expected primary-expression before ‘unsigned’
     return (depth != std::numeric_limits<unsigned int>::min()) && (depth != std::numeric_limits<unsigned int>::max());
                                          ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:87:42: error: expected ‘)’ before ‘unsigned’
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp: At global scope:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:101:9: note: attribute for ‘class cv::RgbdNormals’ must follow the ‘class’ keyword
   class RgbdNormals: public Algorithm
         ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:172:9: note: attribute for ‘class cv::DepthCleaner’ must follow the ‘class’ keyword
   class DepthCleaner: public Algorithm
         ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:274:9: note: attribute for ‘class cv::RgbdPlane’ must follow the ‘class’ keyword
   class RgbdPlane: public Algorithm
         ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:332:21: note: attribute for ‘struct cv::RgbdFrame’ must follow the ‘struct’ keyword
   CV_EXPORTS struct RgbdFrame
                     ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp:42:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:374:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidImage;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:375:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidDepth;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:376:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidMask;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:378:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidCloud;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:380:5: error: ‘vector’ does not name a type
     vector<Mat> pyramid_dI_dx;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:381:5: error: ‘vector’ does not name a type
     vector<Mat> pyramid_dI_dy;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:382:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidTexturedMask;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:384:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidNormals;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:385:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidNormalsMask;
     ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp:42:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:351:21: note: attribute for ‘struct cv::OdometryFrame’ must follow the ‘struct’ keyword
   CV_EXPORTS struct OdometryFrame : public RgbdFrame
                     ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp:42:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:390:20: note: attribute for ‘class cv::Odometry’ must follow the ‘class’ keyword
   CV_EXPORTS class Odometry: public Algorithm
                    ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:495:71: error: ‘vector’ does not name a type
                  float maxDepthDiff = DEFAULT_MAX_DEPTH_DIFF(), const vector<int>& iterCounts = vector<int>(),
                                                                       ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:495:77: error: expected ‘,’ or ‘...’ before ‘<’ token
                  float maxDepthDiff = DEFAULT_MAX_DEPTH_DIFF(), const vector<int>& iterCounts = vector<int>(),
                                                                             ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:494:5: error: default argument missing for parameter 5 of ‘cv::RgbdOdometry::RgbdOdometry(const cv::Mat&, float, float, float, int)’
     RgbdOdometry(const Mat& cameraMatrix, float minDepth = DEFAULT_MIN_DEPTH(), float maxDepth = DEFAULT_MAX_DEPTH(),
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:480:20: note: attribute for ‘class cv::RgbdOdometry’ must follow the ‘class’ keyword
   CV_EXPORTS class RgbdOdometry: public Odometry
                    ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:546:23: error: ‘vector’ does not name a type
                 const vector<int>& iterCounts = vector<int>(), int transformType = RIGID_BODY_MOTION);
                       ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:546:29: error: expected ‘,’ or ‘...’ before ‘<’ token
                 const vector<int>& iterCounts = vector<int>(), int transformType = RIGID_BODY_MOTION);
                             ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:544:5: error: default argument missing for parameter 6 of ‘cv::ICPOdometry::ICPOdometry(const cv::Mat&, float, float, float, float, int)’
     ICPOdometry(const Mat& cameraMatrix, float minDepth = DEFAULT_MIN_DEPTH(), float maxDepth = DEFAULT_MAX_DEPTH(),
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:598:27: error: ‘vector’ does not name a type
                     const vector<int>& iterCounts = vector<int>(),
                           ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:598:33: error: expected ‘,’ or ‘...’ before ‘<’ token
                     const vector<int>& iterCounts = vector<int>(),
                                 ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:596:5: error: default argument missing for parameter 6 of ‘cv::RgbdICPOdometry::RgbdICPOdometry(const cv::Mat&, float, float, float, float, int)’
     RgbdICPOdometry(const Mat& cameraMatrix, float minDepth = DEFAULT_MIN_DEPTH(), float maxDepth = DEFAULT_MAX_DEPTH(),
     ^
/home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp: In function ‘void validateKeyPoints(const std::vector<cv::KeyPoint>&, const cv::Mat&, const cv::Mat&, const cv::Mat&, const cv::Mat&, std::vector<cv::KeyPoint>&, cv::Mat&, cv::Mat&)’:
/home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp:79:27: error: ‘numeric_limits’ is not a member of ‘std’
       float min_dist_sq = std::numeric_limits<float>::max();
                           ^
/home/eriba/catkin_ws/src/ork/tod/src/training/training.cpp:79:47: error: expected primary-expression before ‘float’
       float min_dist_sq = std::numeric_limits<float>::max();
                                               ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:43:0:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:104:31: error: ‘std::map’ has not been declared
                          std::map<Index, Index> &query_inliers);
                               ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:43:0:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:104:31: error: ‘std::map’ has not been declared
                          std::map<Index, Index> &query_inliers);
                               ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:104:34: error: expected ‘,’ or ‘...’ before ‘<’ token
                          std::map<Index, Index> &query_inliers);
                                  ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:104:34: error: expected ‘,’ or ‘...’ before ‘<’ token
                          std::map<Index, Index> &query_inliers);
                                  ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:127:11: error: ‘map’ in namespace ‘std’ does not name a type
   typedef std::map<size_t, AdjacencyRansac> OpenCVIdToObjectPoints;
           ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:127:11: error: ‘map’ in namespace ‘std’ does not name a type
   typedef std::map<size_t, AdjacencyRansac> OpenCVIdToObjectPoints;
           ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:132:20: error: ‘OpenCVIdToObjectPoints’ has not been declared
                    OpenCVIdToObjectPoints &object_points);
                    ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:132:20: error: ‘OpenCVIdToObjectPoints’ has not been declared
                    OpenCVIdToObjectPoints &object_points);
                    ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:136:62: error: ‘OpenCVIdToObjectPoints’ does not name a type
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points);
                                                              ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:136:86: error: ISO C++ forbids declaration of ‘object_points’ with no type [-fpermissive]
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points);
                                                                                      ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:136:62: error: ‘OpenCVIdToObjectPoints’ does not name a type
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points);
                                                              ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.h:136:86: error: ISO C++ forbids declaration of ‘object_points’ with no type [-fpermissive]
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points);
                                                                                      ^
make[2]: *** [ork/tod/src/CMakeFiles/ecto_training_ectomodule.dir/training/training.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:179:20: error: ‘OpenCVIdToObjectPoints’ has not been declared
                    OpenCVIdToObjectPoints &object_points)
                    ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:179:20: error: ‘OpenCVIdToObjectPoints’ has not been declared
                    OpenCVIdToObjectPoints &object_points)
                    ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp: In function ‘void tod::ClusterPerObject(const std::vector<cv::KeyPoint>&, const cv::Mat&, const std::vector<std::vector<cv::DMatch> >&, const std::vector<cv::Mat>&, int&)’:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:202:39: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
         object_points[opencv_object_id].AddPoints(training_point, query_point, query_index);
                                       ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp: At global scope:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:209:62: error: ‘OpenCVIdToObjectPoints’ does not name a type
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points)
                                                              ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:209:86: error: ISO C++ forbids declaration of ‘object_points’ with no type [-fpermissive]
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points)
                                                                                      ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp: In function ‘void tod::ClusterPerObject(const std::vector<cv::KeyPoint>&, const cv::Mat&, const std::vector<std::vector<cv::DMatch> >&, const std::vector<cv::Mat>&, int&)’:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:202:39: error: invalid types ‘int[size_t {aka long unsigned int}]’ for array subscript
         object_points[opencv_object_id].AddPoints(training_point, query_point, query_index);
                                       ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp: In function ‘void tod::DrawClustersPerObject(const std::vector<cv::KeyPoint>&, const std::vector<cv::Scalar_<double> >&, const cv::Mat&, const int&)’:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:214:10: error: ‘OpenCVIdToObjectPoints’ has not been declared
     for (OpenCVIdToObjectPoints::const_iterator query_iterator = object_points.begin();
          ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:214:49: error: expected ‘;’ before ‘query_iterator’
     for (OpenCVIdToObjectPoints::const_iterator query_iterator = object_points.begin();
                                                 ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:215:9: error: ‘query_iterator’ was not declared in this scope
         query_iterator != object_points.end(); ++query_iterator)
         ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:215:41: error: request for member ‘end’ in ‘object_points’, which is of non-class type ‘const int’
         query_iterator != object_points.end(); ++query_iterator)
                                         ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp: At global scope:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:209:62: error: ‘OpenCVIdToObjectPoints’ does not name a type
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points)
                                                              ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:209:86: error: ISO C++ forbids declaration of ‘object_points’ with no type [-fpermissive]
                         const cv::Mat & initial_image, const OpenCVIdToObjectPoints &object_points)
                                                                                      ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp: In function ‘void tod::DrawClustersPerObject(const std::vector<cv::KeyPoint>&, const std::vector<cv::Scalar_<double> >&, const cv::Mat&, const int&)’:
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:214:10: error: ‘OpenCVIdToObjectPoints’ has not been declared
     for (OpenCVIdToObjectPoints::const_iterator query_iterator = object_points.begin();
          ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:214:49: error: expected ‘;’ before ‘query_iterator’
     for (OpenCVIdToObjectPoints::const_iterator query_iterator = object_points.begin();
                                                 ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:215:9: error: ‘query_iterator’ was not declared in this scope
         query_iterator != object_points.end(); ++query_iterator)
         ^
/home/eriba/catkin_ws/src/ork/tod/src/common/adjacency_ransac.cpp:215:41: error: request for member ‘end’ in ‘object_points’, which is of non-class type ‘const int’
         query_iterator != object_points.end(); ++query_iterator)
                                         ^
make[2]: *** [ork/tod/src/CMakeFiles/ecto_detection_ectomodule.dir/common/adjacency_ransac.cpp.o] Error 1
make[1]: *** [ork/tod/src/CMakeFiles/ecto_detection_ectomodule.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
make[2]: *** [ork/tod/src/CMakeFiles/ecto_training_ectomodule.dir/common/adjacency_ransac.cpp.o] Error 1
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:46:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:101:9: note: attribute for ‘class cv::RgbdNormals’ must follow the ‘class’ keyword
   class RgbdNormals: public Algorithm
         ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:172:9: note: attribute for ‘class cv::DepthCleaner’ must follow the ‘class’ keyword
   class DepthCleaner: public Algorithm
         ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:274:9: note: attribute for ‘class cv::RgbdPlane’ must follow the ‘class’ keyword
   class RgbdPlane: public Algorithm
         ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:332:21: note: attribute for ‘struct cv::RgbdFrame’ must follow the ‘struct’ keyword
   CV_EXPORTS struct RgbdFrame
                     ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:46:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:374:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidImage;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:375:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidDepth;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:376:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidMask;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:378:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidCloud;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:380:5: error: ‘vector’ does not name a type
     vector<Mat> pyramid_dI_dx;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:381:5: error: ‘vector’ does not name a type
     vector<Mat> pyramid_dI_dy;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:382:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidTexturedMask;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:384:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidNormals;
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:385:5: error: ‘vector’ does not name a type
     vector<Mat> pyramidNormalsMask;
     ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:46:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:351:21: note: attribute for ‘struct cv::OdometryFrame’ must follow the ‘struct’ keyword
   CV_EXPORTS struct OdometryFrame : public RgbdFrame
                     ^
In file included from /home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:46:0:
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:390:20: note: attribute for ‘class cv::Odometry’ must follow the ‘class’ keyword
   CV_EXPORTS class Odometry: public Algorithm
                    ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:495:71: error: ‘vector’ does not name a type
                  float maxDepthDiff = DEFAULT_MAX_DEPTH_DIFF(), const vector<int>& iterCounts = vector<int>(),
                                                                       ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:495:77: error: expected ‘,’ or ‘...’ before ‘<’ token
                  float maxDepthDiff = DEFAULT_MAX_DEPTH_DIFF(), const vector<int>& iterCounts = vector<int>(),
                                                                             ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:494:5: error: default argument missing for parameter 5 of ‘cv::RgbdOdometry::RgbdOdometry(const cv::Mat&, float, float, float, int)’
     RgbdOdometry(const Mat& cameraMatrix, float minDepth = DEFAULT_MIN_DEPTH(), float maxDepth = DEFAULT_MAX_DEPTH(),
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:480:20: note: attribute for ‘class cv::RgbdOdometry’ must follow the ‘class’ keyword
   CV_EXPORTS class RgbdOdometry: public Odometry
                    ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:546:23: error: ‘vector’ does not name a type
                 const vector<int>& iterCounts = vector<int>(), int transformType = RIGID_BODY_MOTION);
                       ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:546:29: error: expected ‘,’ or ‘...’ before ‘<’ token
                 const vector<int>& iterCounts = vector<int>(), int transformType = RIGID_BODY_MOTION);
                             ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:544:5: error: default argument missing for parameter 6 of ‘cv::ICPOdometry::ICPOdometry(const cv::Mat&, float, float, float, float, int)’
     ICPOdometry(const Mat& cameraMatrix, float minDepth = DEFAULT_MIN_DEPTH(), float maxDepth = DEFAULT_MAX_DEPTH(),
     ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:598:27: error: ‘vector’ does not name a type
                     const vector<int>& iterCounts = vector<int>(),
                           ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:598:33: error: expected ‘,’ or ‘...’ before ‘<’ token
                     const vector<int>& iterCounts = vector<int>(),
                                 ^
/opt/ros/indigo/include/opencv2/rgbd/rgbd.hpp:596:5: error: default argument missing for parameter 6 of ‘cv::RgbdICPOdometry::RgbdICPOdometry(const cv::Mat&, float, float, float, float, int)’
     RgbdICPOdometry(const Mat& cameraMatrix, float minDepth = DEFAULT_MIN_DEPTH(), float maxDepth = DEFAULT_MAX_DEPTH(),
     ^
/home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp: In function ‘void rescale_depth(cv::Mat, const Size&, cv::Mat&)’:
/home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:71:50: error: ‘CV_INTER_NN’ was not declared in this scope
   cv::resize(depth, subregion, subregion.size(), CV_INTER_NN);
                                                  ^
/home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp: In member function ‘int Trainer::process(const ecto::tendrils&, const ecto::tendrils&)’:
/home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:136:15: error: cannot declare variable ‘orb’ to be of abstract type ‘cv::ORB’
       cv::ORB orb;
               ^
In file included from /opt/ros/indigo/include/opencv2/features2d/features2d.hpp:48:0,
                 from /home/eriba/catkin_ws/src/ork/tod/src/training/training.h:37,
                 from /home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:53:
/opt/ros/indigo/include/opencv2/features2d.hpp:163:20: note:   because the following virtual functions are pure within ‘cv::ORB’:
 class CV_EXPORTS_W ORB : public Feature2D
                    ^
/opt/ros/indigo/include/opencv2/features2d.hpp:171:26: note: 	virtual void cv::ORB::setMaxFeatures(int)
     CV_WRAP virtual void setMaxFeatures(int maxFeatures) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:172:25: note: 	virtual int cv::ORB::getMaxFeatures() const
     CV_WRAP virtual int getMaxFeatures() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:174:26: note: 	virtual void cv::ORB::setScaleFactor(double)
     CV_WRAP virtual void setScaleFactor(double scaleFactor) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:175:28: note: 	virtual double cv::ORB::getScaleFactor() const
     CV_WRAP virtual double getScaleFactor() const = 0;
                            ^
/opt/ros/indigo/include/opencv2/features2d.hpp:177:26: note: 	virtual void cv::ORB::setNLevels(int)
     CV_WRAP virtual void setNLevels(int nlevels) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:178:25: note: 	virtual int cv::ORB::getNLevels() const
     CV_WRAP virtual int getNLevels() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:180:26: note: 	virtual void cv::ORB::setEdgeThreshold(int)
     CV_WRAP virtual void setEdgeThreshold(int edgeThreshold) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:181:25: note: 	virtual int cv::ORB::getEdgeThreshold() const
     CV_WRAP virtual int getEdgeThreshold() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:183:26: note: 	virtual void cv::ORB::setFirstLevel(int)
     CV_WRAP virtual void setFirstLevel(int firstLevel) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:184:25: note: 	virtual int cv::ORB::getFirstLevel() const
     CV_WRAP virtual int getFirstLevel() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:186:26: note: 	virtual void cv::ORB::setWTA_K(int)
     CV_WRAP virtual void setWTA_K(int wta_k) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:187:25: note: 	virtual int cv::ORB::getWTA_K() const
     CV_WRAP virtual int getWTA_K() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:189:26: note: 	virtual void cv::ORB::setScoreType(int)
     CV_WRAP virtual void setScoreType(int scoreType) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:190:25: note: 	virtual int cv::ORB::getScoreType() const
     CV_WRAP virtual int getScoreType() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:192:26: note: 	virtual void cv::ORB::setPatchSize(int)
     CV_WRAP virtual void setPatchSize(int patchSize) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:193:25: note: 	virtual int cv::ORB::getPatchSize() const
     CV_WRAP virtual int getPatchSize() const = 0;
                         ^
/opt/ros/indigo/include/opencv2/features2d.hpp:195:26: note: 	virtual void cv::ORB::setFastThreshold(int)
     CV_WRAP virtual void setFastThreshold(int fastThreshold) = 0;
                          ^
/opt/ros/indigo/include/opencv2/features2d.hpp:196:25: note: 	virtual int cv::ORB::getFastThreshold() const
     CV_WRAP virtual int getFastThreshold() const = 0;
                         ^
/home/eriba/catkin_ws/src/ork/tod/src/training/Trainer.cpp:137:54: error: no match for call to ‘(cv::ORB) (cv::Mat&, cv::Mat&, std::vector<cv::KeyPoint>&, cv::Mat&)’
       orb(obs.image, obs.mask, keypoints, descriptors);
                                                      ^
make[2]: *** [ork/tod/src/CMakeFiles/ecto_training_ectomodule.dir/training/Trainer.cpp.o] Error 1
make[1]: *** [ork/tod/src/CMakeFiles/ecto_training_ectomodule.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by edgarriba** [comment]
fixed with 27a98773762cd086eb02b5a45fcc85286ec89c7f
